# Generated by Django 5.1.5 on 2025-02-01 06:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Enter the question in English')),
                ('answer', ckeditor.fields.RichTextField(help_text='Enter the answer in English')),
                ('question_hi', models.TextField(blank=True, help_text='Hindi translation of the question', null=True)),
                ('answer_hi', ckeditor.fields.RichTextField(blank=True, help_text='Hindi translation of the answer', null=True)),
                ('question_bn', models.TextField(blank=True, help_text='Bengali translation of the question', null=True)),
                ('answer_bn', ckeditor.fields.RichTextField(blank=True, help_text='Bengali translation of the answer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at'],
            },
        ),
    ]
